### ISSUE TITLE
Grid column width is wrongly calculated when reattaching component

### ISSUE THREAD

**Issue by wbadam** [vaadin/framework#10438]
Framework 8.1.7

When a Grid is hidden and then later shown with `grid.setVisible()` method, when it is displayed the second time, the column widths are miscalculated.

The reason is that showing the Grid requests the data to be sent from the server (hidden Grid loses cached data), and due to scheduling, column widths are calculated prior to the Grid being populated. This makes Grid to calculate it's column widths according to header length rather than all data.

To test, create a Grid, and toggle its visibility with a button.

**Comment by TatuLund** [comment]
This issue is fixed as byproduct of https://github.com/vaadin/framework/pull/10579

**Comment by ldelaprade** [comment]
I still have this exact same bug with version : <vaadin.version>8.4.5</vaadin.version>


//when detaching MY_GRID from AbsoluteLayout to replace it with a TabSheet:
    extendedModeTabSheet = new TabSheet();
    extendedModeTabSheet.setWidth("100%");
    extendedModeTabSheet.setHeight("100%");    
    originalTableParent.replaceComponent(MY_GRID, extendedModeTabSheet);
    
// then move the Grid from original Layout to a new one using original position
    AbsoluteLayout newTableParentLayout = new AbsoluteLayout();
    newTableParentLayout.setSizeFull();
    newTableParentLayout.addComponent(MY_GRID, originalpos.getCSSString());
// then pushing the new Absolute Layout as the first tab page 
    extendedModeTabSheet.addTab(newTableParentLayout, "Table");

Then, all grid columns are collapsed to minimal size instead of spreading through accross available width
