### ISSUE TITLE
Issues with @PushStateNavigation if the application is not deployed in the root context

### ISSUE THREAD

**Issue by Zixxl** [vaadin/framework#10633]
I have a problem when using @PushStateNavigation together with the annotation @CDIUI ("") and deploying the application on an application server under a context path.

When using the annotation @CDIUI ("") the uiPathInfo is set to "/". With a function in the class com.vaadin.ui.UI, the context path is then removed from the uiRootPath. The function is: 

uiRootPath = uiRootPath.substring(0, uiRootPath.indexOf(uiPathInfo) + uiPathInfo.length());

As an example, the application is deployed under the context path "/MyUI". The uiRootPath "/MyUI" will be translated to "/". So navigating to a view with the name "login" will cause the PushStateNavigation to set the url to "http://server/login" instead of "http://server/MyUI/login". If, on the other hand, the annotation @CDIUI ("test") is used, uiPathInfo is set to "/test" and the function translates "/MyUI/test" to "/MyUI/test" and everything is working fine. But in this case the UI is not longer located in the root under the context path.

Tested under Vaadin version 8.3.0.

**Comment by TatuLund** [comment]
There is releated discussion in the Forum: https://vaadin.com/forum/#!/thread/16972282

**Comment by Zixxl** [comment]
I don't think that this issue is only related to the CDI addon. This error should also occur with the Spring addon and a classic implementation.

**Comment by tsuoanttila** [comment]
Needs to be tested separately for the Spring add-on. I will add integration tests for this specific use-case.

**Comment by Zixxl** [comment]
Tested with classic implementation. The uiPathInfo in the test case is null, so the rootPathInfo is set correctly. So it seems an issue with the addons (i didn't test the spring addon).

**Comment by cyberoblivion** [comment]
I can confirm that the spring addon also exhibits the above described behavior

**Comment by cyberoblivion** [comment]
Shouldn't this be fixed in UI.java? 
Would it be ok if we just changed line 739 like this. Then both addons maybe work ok.

` String uiPathInfo = request.getContextPath() + request
                .getAttribute(ApplicationConstants.UI_ROOT_PATH);`

I tested this with spring addon and it seemed to work.

**Comment by cyberoblivion** [comment]
Has this been addressed for Spring Addon?
This issue makes PushStateNavigation useless for a large number of users I would think, including us. 

I couldn't find an issue open in the Spring Addon issues. Should I open an issue? I would like to prioritize this with our prime subscription but I need an open issue.

**Comment by aricooperman** [comment]
This is in fact still an issue with Spring add-on/starter and not just a CDI issue. I am using V8 and have been for years on top of Spring. I have always had an /api/** path that has been handled by Spring Controllers and I have a main UI mapped to "/". Once I add push state navigation to this UI, everything gets routed to this UI as in com.vaadin.spring.boot.internal.VaadinServletConfiguration#getUIPaths this occurs:

```
 if (hasPushStateNavigation) {
                path = getWildcardedPath(path);
            }
```

which then becomes "/**/" and everything goes to MainUI
