### ISSUE TITLE
All TreeGrid rows collapse after expanding certain rows.

### ISSUE THREAD

**Issue by eriklumme** [vaadin/framework#10651]
Vaadin Framework version: 8.3.1
Browser: Chrome 64.0.3282.167

Expected outcome: 
When expanding a row, it stays expanded.

Actual outcome:
When expanding any of the first 3 rows, the grid immediately collapses all rows.
When expanding row 4, it collapses if one item below it is already expanded.
When expanding row 5, it collapses if two items below it are already expanded. Etc.
(Also depends on number of children).

```Java
@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();

        TreeGrid<Project> treeGrid = new TreeGrid<>();
        treeGrid.setDataProvider(new MyDataProvider());

        treeGrid.addColumn(Project::getName).setCaption("Project Name");

        layout.addComponent(treeGrid);

        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }

    static class Project {
        private String name;
        private boolean hasChildren;

        public Project(String name, boolean hasChildren) {
            this.name = name;
            this.hasChildren = hasChildren;
        }

        public String getName() {
            return name;
        }

        public boolean isHasChildren() {
            return hasChildren;
        }
    }

    static class MyDataProvider extends
        AbstractBackEndHierarchicalDataProvider<Project, Void> {

        @Override
        protected Stream<Project> fetchChildrenFromBackEnd(HierarchicalQuery<Project, Void> query) {
            if(query.getParentOptional().isPresent()) {
                return Stream.of(new Project("Child", false));
            }
            return IntStream.range(1, 9).mapToObj(i -> new Project("Parent " + i, true));
        }

        @Override
        public int getChildCount(HierarchicalQuery<Project, Void> query) {
            if(query.getParentOptional().isPresent()) {
                return query.getParent().hasChildren ? 1 : 0;
            }
            return 8;
        }

        @Override
        public boolean hasChildren(Project item) {
            return item.hasChildren;
        }
    }
}
```

**Comment by eriklumme** [comment]
Solved with proper `equals` and `hashCode` implementations.

**Comment by ojanovsky** [comment]
Hello,
The issue still exists in 8.7.2 . The TreeGrid is totally unusable.
