### ISSUE TITLE
Session Expires After 10 minutes using Jetty 9.4

### ISSUE THREAD

**Issue by Flamenco** [vaadin/framework#10898]
Vaadin 8.4.1

Jetty 9.4 now has a thread that prunes sessions.  By default it is 10 minutes.  The session's lastaccessedtime is not updated by Vaadin or Atmosphere, although the heartbeats are sent and received.

So the issues are why is the lastaccessedtime not updated, and possibly why that the scavenge interval should be synced to be higher than the default setting.

At the very least this behavior should be documented, as it cost me quite a bit of time tracking it down.

Workaround:
I set the scavenge interval to be a giant number to get things working again. 

To Reproduce, run Vaadin in Karaf 4.2.0.

**Comment by Flamenco** [comment]
This is still a problem, even with the workaround.  @elmot any ideas on how to get the sessions to stay alive with Jetty 9.4?

**Comment by Flamenco** [comment]
> Jetty 9.3.21.v20170918 

Yes it works well.  I was using 4.2-SNAPSHOT and had no problems until they released the final version with the updated Jetty.

**Comment by Flamenco** [comment]
Workaround:

I rebuild Karaf, the most recent master branch, but changed the pax-web feature version it is build with to 6.1.2 (from 7.0.0)  That pulled in a working version of Jetty and things work as expected.

Can someone from Vaadin reply if this is a Vaadin or Atmosphere issue?  It's really a critical deal breaker for Vaadin.

**Comment by elmot** [comment]
I am afraid we can not reply quickly. We need to investigate the case.

Related to #10916

**Comment by TatuLund** [comment]
According to https://github.com/Atmosphere/atmosphere/issues/2324 the issue should be addressed in 2.4.25 version of Atmosphere and PR https://github.com/vaadin/framework/pull/11122 upgrades Atmosphere in Vaadin to 2.4.30 based version. It is already in 8.6-SNAPSHOT, so it should be possible to verify if it works now.

**Comment by Flamenco** [comment]
@TatuLund, if I set `Atmosphere` to timeout every 10 seconds by changing `org.atmosphere.websocket.maxIdleTime`, my client just keeps reconnecting.  I still have these same reported issues though, so  I cannot see how Atmosphere/atmosphere#2324 is going to solve this.

As stated, the issue is related to the changes in `Jetty 9.4` session architecture.

Because I downloaded Karaf 4.2.1 yesterday and wanted to play with my new toy, I traced through all of  `Vaadin 8.5.1` and `Jetty 9.4.x` source code to find the real problem. Pretty sure I fixed it;  It is now deployed in production and will certainly hear back from my users today if I did not.

**Comment by arotnov** [comment]
Then using websocket transport, any of vaadin messages will be sended in websocket channel (not only push messages), and `lastAccessedTime` of HttpSession will not been updated.
Vaadin sends `heartbeat` http requests regarless of push transport type. Heartbeat message updates `lastAccessedTime` and keep session alive. If `maxInactiveInterval` of http session is the same as `heartbeatInterval`, session expired before (i think is right after first) second heartbeat message, and after sending it, response result code will be 301 (session expired).
By default `maxInactiveInterval` is 300 seconds, vaadin `heartbeatInterval` is also 300 seconds. So after 600 seconds, you have an expired session.
After `org.atmosphere.websocket.maxIdleTime` is a elapsed, websocket will be closed, and vaadin try to reesatblish connection by sending handshake request (to URL like ws://host:port/PUSH), and if session is not expired, connection will be reestablished. 
So, to solve your problem just set `maxInactiveInterval` more than `heartbeatInterval`.

**Comment by Flamenco** [comment]
@arotnov I am sorry, but you are incorrect.  That does not work.  Please try solution before posting.  The heartbeats are received but do not reset the session’s internal counter.  I an set the heartbeat interval to 10 seconds and Vaadin will still break.

**Comment by arotnov** [comment]
@Flamenco Okay, maybe we have different environment, or settings.
Here `https://github.com/arotnov/sandbox/tree/master/vaadin-osgi-websockets` I prepare sample project (for clean Karaf 4.2.1) to show, that I'm right. 
In `VaadinServletRegistration` I publish VaadinServlet as a OSGi service with heartbeat interval = 10 sec and `org.atmosphere.websocket.maxIdleTime` = 30 sec. Session timeout = 1 minute specified in `vaadin-osgi-kar` feature config:
`<config name="org.ops4j.pax.web" append="true">
org.ops4j.pax.web.session.timeout=1 
</config>`

**Comment by Flamenco** [comment]
@arotnov Have you left your session idle for >60 minutes with this configuration?

**Comment by arotnov** [comment]
@Flamenco Yes. It works as mentioned above.

**Comment by Flamenco** [comment]
@arotnov 

* Pulled down latest Karaf
* Added all bundles for Vaadin, Vaadin-Push, and Vaadin-Atmosphere
* Added a UI and servlet with push enabled
* Set my heartbeat to 10 seconds

I should not have to set anything else. I even tried to set closeIdleSessions to false (the default).   I am even pushing to the client every second.

Still times out at 10 minutes as mentioned in original post.  As I have stated, the heartbeats do not work on Jetty 9.4.

I am build via gradle BTW.

**Comment by Flamenco** [comment]
Here is my bundle list.
```
 23 │ Active   │  80 │ 4.2.1             │ Apache Karaf :: OSGi Services :: Event
 45 │ Active   │  80 │ 0.0.0             │ test.feature.xml
 46 │ Active   │  80 │ 1.2.0.vaadin1     │ GenTyRef
 47 │ Active   │  80 │ 8.5.2             │ Vaadin OSGi Integration
 48 │ Active   │  80 │ 8.5.2             │ Vaadin Server
 49 │ Active   │  80 │ 8.5.2             │ Vaadin Shared
 50 │ Active   │  80 │ 8.5.2             │ Vaadin Themes
 63 │ Active   │  80 │ 4.6.0             │ Apache XBean OSGI Bundle Utilities
 64 │ Active   │  80 │ 4.6.0             │ Apache XBean :: Classpath Resource Finder
 92 │ Active   │  80 │ 1.11.3            │ jsoup Java HTML Parser
 93 │ Active   │  80 │ 6.2.0             │ org.objectweb.asm
 94 │ Active   │  80 │ 6.2.0             │ org.objectweb.asm.commons
 95 │ Active   │  80 │ 6.2.0             │ org.objectweb.asm.tree
102 │ Active   │  80 │ 0.0.0.unspecified │ vaadin-karaf-websocket-test-project
103 │ Active   │  80 │ 1.1.2.2           │ kotlin-osgi-bundle
104 │ Active   │  80 │ 8.5.2             │ Vaadin Push
112 │ Active   │  80 │ 2.4.30.vaadin1    │ atmosphere-runtime
113 │ Active   │  80 │ 1.6.1             │ vaadin-slf4j-jdk14
114 │ Resolved │  80 │ 1.0.0.SNAPSHOT    │ tv.twelvetone.medusa.components.websocket_fragment, Hosts: 55
```

**Comment by Flamenco** [comment]
My Servlet
```
@Component(service = arrayOf(VaadinServlet::class))
@WebServlet(
        asyncSupported = true,
        urlPatterns = arrayOf("/*", "/VAADIN/*"),
        initParams = arrayOf(
                WebInitParam(name = "ui", value = "com.example.vaadinkarafwebsockettestproject.VaadinKarafWebsocketTestProjectUI"),
                WebInitParam(name = "productionMode", value = "true"),
                WebInitParam(name = "closeIdleSessions", value = "false"),
                WebInitParam(name = "heartbeatInterval", value = "10")
        ))
class VaadinKarafWebsocketTestProjectServlet : VaadinServlet()
```

@arotnov As previously stated, when I rebuild Karaf core using early versions of Jetty 9.3, I have no problems.

**Comment by Flamenco** [comment]
And I use a fragment hack as well. :)

**Comment by Flamenco** [comment]
One difference in our production build is all Vaadin bundles are inside an uber-jar.  We will split this up tomorrow and post test reults.

**Comment by TatuLund** [comment]
Has anyone tested 8.6.0.beta1 release https://vaadin.com/framework/releases/8.6.0.beta1 which has updated version of Atmosphere?

**Comment by Flamenco** [comment]
@TatuLund We are using 2.4.30.vaadin1 and Jetty 9.4.11.v20180605.

**Comment by Flamenco** [comment]
@TatuLund @arotnov  I can confirm this issue is FIXED in 8.6.0.beta1, and perhaps in 8.5.2

The lastaccessedtime of the session is now correctly getting reset when the heartbeat arrives.

**There is one caveat however**:
The heartbeat (in seconds) must be lower than the org.ops4j.pax.web.session.timeout (in minutes) by at least 1/3.  When the heartbeat arrives, the lastaccessedtime is set to the current time + the heartbeat value.  So if the delta of now and lastaccessedtime is 80 seconds, and the heartbeat is 60 seconds, the delta becomes 60 seconds, not 0 as would be expected.  So if the heartbeat is 1/2 of the session timeout, you will run into issues.

Another issue is if using push, Vaadin should send a message to the client when session expires so a heartbeat or user interaction is not required before showing the session-expired dialog.  That really pisses of my users.  A frequent heartbeat helps, but is not ideal.  I will save that for another post...

**Comment by ZheSun88** [comment]
@Flamenco Thanks for the feedback and i am going to close this ticket as the issue is fixed in the latest release. You can open another ticket for the other issues.
