### ISSUE TITLE
Grid Multiselect does not change selection on filtering or other data change

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#11488]
This is related to #11479 

### Steps to Reproduce
I have a grid to select multiple items and a ListDataProvider with filtering. 

* Select 5 rows - the `getSelectedItems` returns five items.
* Filter out selected items.
* The `getSelectedItems` still returns previous 5 items and selection changed listener was not called.

### Expected Behavior
The `getSelectedItems` should return only available items and selection changed listener should be called.

### Actual Behavior
* The `getSelectedItems` returns items no longer available. Selection changed listener was not called.

**Comment by TatuLund** [comment]
This should be addressed by https://github.com/vaadin/framework/pull/11790

**Comment by stefanuebe** [comment]
Unfortunately it doesn't seem to be fixed. We have a same issue still in 8.11.1 (using a TreeGrid with single select and calling `getSelectedItems()`.

Our steps:
* Populate the data to the grid
* Select an item
* Delete this item by using a simple button
* Remove the data from the backend
* Call `refreshAll` on the Grid's DataProvider
* The hierarchical data is fully rebuilt (and, as expected, does not contain the deleted element)
* Calling `getSelectedItems()` returns the deleted item

The `isSelected()` method is called later during the lifecycle when updating the client side, but the server side still has the item selected.

**Comment by Ansku** [comment]
You are right, the mentioned patch fixed a visual selection bug on the client-side, this one seems to be about the server-side logic. I'll take a look to see if this is fixable or something that needs to be worked around (selection isn't saved within DataProvider so keeping those states consistent might not be trivial).

**Comment by Ansku** [comment]
Unfortunately this doesn't seem to be fixable on the framework level. The potential fix that I was thinking about does fix the situation in a trivial case, but as an unfortunate side effect it would also remove the selection from any rows that are scrolled outside of cache if any other row gets removed, and that would be unacceptable. And adding a check that relies on querying the entire data set would be inadvisable for performance reasons and not necessarily even supported by all data sets. Furthermore, as the removal and selection check would have to happen in entirely different locations, there is no way to limit the check specifically to the rows that get removed from the data set entirely rather than only from the cache. The best way to deal with the issue is likely to check the selection when you remove a row and update the selection accordingly if needed.

As for filtering updating the selection, personally I think that would be somewhat questionable as the default behavior, even if it makes a lot of sense for some specific use cases. A similar workaround should do the trick there as well.
