### ISSUE TITLE
MenuBar highlight ring is misshapen in Chrome 76-77

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#11720]
Vaadin 8.9.0, probably affects earlier versions as well.
In Chrome 76+, the focus ring around MenuBar is not rectangular for some reason.
Reproduces in Sampler:
![image](https://user-images.githubusercontent.com/15027701/64782065-0abfbc00-d56d-11e9-85f6-4131d7125581.png)

Tested on Windows 10.

**Comment by TatuLund** [comment]
I tried to replicate the issue with the latest chrome and I could not, so it looks like that this issue has been fixed in Chrome 78.

**Comment by echarlus** [comment]
I just tried with chrome Version 78.0.3904.70 on MacOS and the issue is still present (see attached screenshot).
<img width="461" alt="Capture d’écran 2019-10-28 à 09 18 21" src="https://user-images.githubusercontent.com/7509875/67662545-f3456280-f963-11e9-8448-7d683cec0e30.png">

**Comment by TatuLund** [comment]
I see, I did my testing on Windows 10, so clearly the behavior is different depending on OS now.

**Comment by TatuLund** [comment]
This issue should be possible to tackled in application custom styles with the following workaround

```
/* Disable default browser generated focus ring */
.v-menubar-menuitem {
    outline: 0;
}

/* Implement focus ring with box-shadow on focus */ 
.v-menubar-menuitem:focus { 
    box-shadow: 0px 0px 0px 2px #81BDFD;
}
```

**Comment by TatuLund** [comment]
The appearance has changed a bit with the latest Chrome, there still slight artifact when zoomed, but not as bad

![image](https://user-images.githubusercontent.com/14309836/108165809-d8b86f00-70fb-11eb-99c1-b4fb6300296a.png)

**Comment by TatuLund** [comment]
I have not been following this for every Chrome release, but with current (i.e. 95) one it looks like this, so it seems to have been fixed by some of the latest Chrome versions

![image](https://user-images.githubusercontent.com/14309836/141981000-1bf97472-4992-4f51-8853-bda95b20e9b0.png)
