### ISSUE TITLE
Disabled checkboxes or radio buttons can't be seen from the UI

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8579]
### Description of the bug

Disabled option in CheckboxGroup or RadioButtonGroup looks exactly like normal option, making end user think that the UI is broken when trying to select disabled option.

### Example code to reproduce

        RadioButtonGroup single = new RadioButtonGroup("Single Selection");
        single.setItems("Single", "Sola", "Yksi");
        single.setItemEnabledProvider(s->!"Sola".equals(s));
        single.setId("single-optiongroup");

**Comment by pleku** [comment]
Regression from V7, missing the e.g. `v-radiobutton-disabled v-disabled` class names (and corresponding to CBG).

**Comment by Saxintosh** [comment]
Please... it's still to fix in the last 8.1.5....
Thanks.

**Comment by jarrah42** [comment]
I just came across this problem, so I'll add my support for this getting fixed.

**Comment by mstahv** [comment]
@tsuoanttila Wasn't this fixed in the latest bugfix release this week? I think there was another issue for it.

**Comment by tsuoanttila** [comment]
Yes. #9258 in 8.1.7. Closing as duplicate.

**Comment by Saxintosh** [comment]
Still broken!

it requires a refreshAll() broadcasted after the UI was showed:

        rbg = new RadioButtonGroup<>("My Disabled Group");
        rbg.setItems("One", "Two", "Three");

        rbg.setItemEnabledProvider(item-> !"Two".equals(item)); // doesn't work
        rbg.getDataProvider().refreshAll(); // still doesn't work


        Button button = new Button("Click Me");
        button.addClickListener(e -> {
            rbg.getDataProvider().refreshAll(); // now it works!!!
        });

**Comment by timothygruetzner** [comment]
Comment by "Saxintosh" confirmed. Opened new issue https://github.com/vaadin/framework/issues/10712
